version: '3.8'

services:
  frontend:
    image: estoqfy-frontend
    build:
      context: ./Estoqfy
      dockerfile: Dockerfile
    ports:
      - "80:80"  # Expõe a porta 80 do container na porta 80 do host
    networks:
      - api-network
    depends_on:
      - api
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  api:
    image: estoqfy-api
    build:
      context: ./EstoqfyApi
      dockerfile: Dockerfile
    ports:
      - "5000:80"  # Expõe a porta 80 do container na porta 5000 do host
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=db;Port=3306;Database=estoqfy_db;User Id=user;Password=password
    networks:
      - api-network
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - api-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  api-network:
    driver: bridge

volumes:
  mariadb_data: