---
services:
  frontend:
    build:
      context: ./Estoqfy
      dockerfile: Dockerfile
    ports:
      - 80:3000
    networks:
      - api-network
    restart: always
  api:
    build:
      context: ./EstoqfyApi
      dockerfile: Dockerfile
    ports:
      - 5000:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=db;Port=3306;Database=${DB_NAME};User
        Id=${DB_USER};Password=${DB_PASSWORD}
    networks:
      - api-network
    depends_on:
      db:
        condition: service_healthy
    restart: always
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - api-network
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - -h
        - localhost
      interval: 10s
      timeout: 20s
      retries: 10
    restart: always
networks:
  api-network:
    driver: bridge
volumes:
  mariadb_data: null
