---
services:
  frontend:
    container_name: front-estoqfy
    build:
      context: ./Estoqfy
      dockerfile: Dockerfile
    ports:
      - 3000:3000 
    depends_on:
      - api
    volumes:
      - ./Estoqfy:/app
    environment:
      - NUXT_HOST=0.0.0.0
      - NUXT_PORT=3000
  api:
    build:
      context: ./EstoqfyApi
      dockerfile: Dockerfile
    container_name: api-estoqfy
    ports:
      - 8080:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_ROOT_PASSWORD}
    depends_on:
      - db
    restart: always
    env_file:
      - .env

  db:
    image: mariadb:latest
    container_name: db-estoqfy
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: always
    env_file:
      - .env

  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/ssl/certs/nginx-selfsigned.crt:/etc/ssl/certs/nginx-selfsigned.crt
      - /etc/ssl/private/nginx-selfsigned.key:/etc/ssl/private/nginx-selfsigned.key

volumes:
  mariadb_data: