version: '3.8'

services:
  api:
    image: estoqfy:dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - api-network

networks:
  api-network:
    driver: bridge